services:
  server:
    image: scmp-server:v1.1
    build:
      context: ./server
    ports:
      - 5000:5000
    environment:
      # DEVELOPMENT
      - NODE_ENV=production
      - PORT=5000

      # DATABASE
      - LOCAL_DB=mongodb+srv://janaashamii:janashami1234@cluster0.cjdjvqk.mongodb.net/?retryWrites=true&w=majority

      # JWT
      - JWT_SECRET=icunhr3947nyv9y9ryvanoergnv8qoiuerntvigweoirhnvuhtn7tnv934yht9pvvhapoiwehn3984v
      - JWT_EXPIRES=7d
      - COOKIE_EXPIRES=7

      # CLOUDINARY
      - CLOUDINARY_CLOUD_NAME=dunzcbcnb
      - CLOUDINARY_API_KEY=637414892488137
      - CLOUDINARY_API_SECRET=d0iM-YIul-uMuy_iH5DteafAPCM

    volumes:
      - ./server:/app:cache
      - /app/node_modules
    networks:
      - mern-app
    # depends_on:
    #   - mongo

  client:
    image: scmp-client:v1.1
    stdin_open: true
    build:
      context: ./client
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
      - http_proxy=http://server:5000
    volumes:
      - ./client:/app:cache
      - /app/node_modules
    networks:
      - mern-app
    depends_on:
      - server

networks:
  mern-app:
    driver: bridge
#   mongo:
#     container_name: mongo-db
#     image: mongo
#     ports:
#       - 27018:27017
#     volumes:
#       - mongo-data:/data/db
#     networks:
#       - mern-app
#     logging:
#       driver: none

# volumes:
#   mongo-data:
#     driver: local
