services:
  server:
    image: mohamad98/scmp-server:v1.1
    ports:
      - 5000:5000
    environment:
      # DEVELOPMENT
      - NODE_ENV=production
      - PORT=5000

      # DATABASE
      - LOCAL_DB=mongodb+srv://janaashamii:janashami1234@cluster0.cjdjvqk.mongodb.net/?retryWrites=true&w=majority

      # JWT
      - JWT_SECRET=icunhr3947nyv9y9ryvanoergnv8qoiuerntvigweoirhnvuhtn7tnv934yht9pvvhapoiwehn3984v
      - JWT_EXPIRES=7d
      - COOKIE_EXPIRES=7

      # CLOUDINARY
      - CLOUDINARY_CLOUD_NAME=dunzcbcnb
      - CLOUDINARY_API_KEY=637414892488137
      - CLOUDINARY_API_SECRET=d0iM-YIul-uMuy_iH5DteafAPCM
    networks:
      - scmp-test

  client:
    image: mohamad98/scmp-client:v1.1
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - http_proxy=http://server:5000
    networks:
      - scmp-test
    depends_on:
      - server

networks:
  scmp-test:
    driver: bridge
